name: Jekyll site CI

on:
  schedule:
    - cron: 0 */12 * * *
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get access token
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_KEY: ${{ secrets.APP_KEY }}
      shell: bash
      run: |
        curl --location 'https://auth.hyperverge.co/login' --header 'Content-Type: application/json' --data '{"appId": "${APP_ID}", "appKey": "${APP_KEY}", "expiry": 86400}' > auth.json
    - name: Get access token
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_KEY: ${{ secrets.APP_KEY }}
      shell: bash
      run: |
        echo 'https://auth.hyperverge.co/login' --header 'Content-Type: application/json' --data '{"appId": "${APP_ID}", "appKey": "${APP_KEY}", "expiry": 86400}'
    - name: Commit files
      run: | 
        git config --local user.email "kalanithi.jp@hyperverge.co"
        git config --local user.name "KalanithiJP"
        git add .
        git commit -m "Access token generated"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
